### ISSUE TITLE
sharing of post with facebook and google plus

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#9]
The sharing feature on the blog and job log section using facebook and google plus doesnt appear to work correctly as it doesnt show the correct information summary. This issue doesnt seem to happen with twitter and the others.

Please fix for both facebook and google plus

**Comment by mklmotors** [comment]
update on this please

**Comment by bikash02** [comment]
Its not working due to facebook open graph meta misconfiguration.
Kindly check  the below link
http://www.mklmotors.com/blog/2016/02/16/free-tyre-pressure-checker-tool/
Note: Some of the posts having featured image and some have in the editor.So there was problem while fetching og:image meta content.

**Comment by mklmotors** [comment]
is it now working properly?

**Comment by debdiproy** [comment]
Will check this properly and revert back to you by tomorrow Khaled

**Comment by bikash02** [comment]
Resolved the issue.Kindly check from your end and let me know your feedback.

**Comment by mklmotors** [comment]
great work bikash
